version: '3.8'

services:

  editor-backend:
    build:
      context: ./editor-backend
    container_name: editor-backend
    ports:
      - "9000:8000"
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./editor-backend:/usr/src/app
    networks:
      - workflow-editor-net

  editor-frontend:
    build:
      context: ./editor-frontend
    container_name: editor-frontend
    ports:
      - "3001:3000"
    restart: always
    volumes:
      - ./editor-frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - workflow-editor-net

  workflow-frontend:
    build:
      context: ./frontend
    container_name: workflow-frontend
    ports:
      - "3002:3000"
    restart: always
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - workflow-editor-net

  workflow-backend:
    build:
      context: ./backend
    container_name: workflow-backend
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend:/usr/src/app
    networks:
      - workflow-editor-net
    depends_on:
      - workflow-db

  workflow-db:
    image: postgres:16-alpine3.20
    container_name: workflow-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workflow
    volumes:
      - workflow-db-data:/var/lib/postgresql/data
    networks:
      - workflow-editor-net

networks:
  workflow-editor-net:
    external: true

volumes:
  workflow-db-data:
    external: true
