# Generated by Django 4.2.3 on 2024-02-12 11:54

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteDocument',
            fields=[
                ('_id', models.TextField(primary_key=True, serialize=False)),
                ('document_name', models.JSONField()),
                ('company_id', models.JSONField()),
                ('collection_id', models.JSONField()),
                ('favourited_by', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteTemplate',
            fields=[
                ('_id', models.TextField(primary_key=True, serialize=False)),
                ('company_id', models.JSONField()),
                ('collection_id', models.JSONField()),
                ('template_name', models.JSONField()),
                ('favourited_by', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteWorkflow',
            fields=[
                ('_id', models.TextField(primary_key=True, serialize=False)),
                ('company_id', models.JSONField()),
                ('workflows', models.JSONField()),
                ('favourited_by', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessReminder',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('process_id', models.TextField()),
                ('step_finalizer', models.TextField()),
                ('email', models.JSONField()),
                ('interval', models.JSONField()),
                ('last_reminder_datetime', models.JSONField()),
                ('created_by', models.TextField(max_length=200)),
            ],
        ),
    ]
